# Generated by Django 5.1.6 on 2025-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_equipment_image_url_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantingarea',
            options={'verbose_name': 'Tree Location', 'verbose_name_plural': 'Tree Locations'},
        ),
        migrations.RenameField(
            model_name='plantingarea',
            old_name='name',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='plantingarea',
            name='location',
        ),
        migrations.RemoveField(
            model_name='plantingarea',
            name='size_in_sq_meters',
        ),
        migrations.AddField(
            model_name='plantingarea',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantingarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
